FROM flink:1.19.3-scala_2.12-java17

USER root

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      ca-certificates \
      curl \
      docker.io \
 && rm -rf /var/lib/apt/lists/*

RUN docker --version

USER flink
